import type { Metadata } from "next";
import { Instrument_Serif, Plus_Jakarta_Sans, Geist } from "next/font/google";
import "./globals.css";
import { LenisProvider } from "./providers/lenis-provider";
import NavBar from "@/components/NavBar";
import { cn } from "@/lib/utils";
import Footer from "@/components/Footer";
import PageTransitionContent, {
  PageTransitionProvider,
} from "@/components/PageTransition";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", plusJakartaSans.variable, instrumentSerif.variable, "font-sans", geist.variable)}
    >
      <body className="bg-background">
        <LenisProvider>
          <PageTransitionProvider>
            <NavBar />
            <main>
              <PageTransitionContent>{children}</PageTransitionContent>
            </main>
            <Footer />
          </PageTransitionProvider>
        </LenisProvider>
      </body>
    </html>
  );
}
